### ISSUE TITLE
Knative Serving bundles an Istio client

### ISSUE THREAD

**Issue by silverlyra** [aspenmesh/istio-client-go#11]
Thanks for implementing this – it’s super frustrating that Istio doesn’t expose a Kubernetes API client, despite being implemented in Go.

I was looking into implementing an operator that would need to watch Istio `Gateway`s, and noticed that wasn’t part of this package. I went looking for an alternative and discovered that [Knative Serving](https://github.com/knative/serving), which wraps Istio, includes [an API client](https://godoc.org/github.com/knative/pkg/apis/istio) for it. It looks like it solves #1 by implementing the API types itself.

Just wanted to flag it for you if you’d like an Istio client that you wouldn’t have to maintain 😛

**Comment by nrjpoddar** [comment]
Thanks @silverlyra for pointing to the Knative implementation which is helpful but since they have a copy of the generated go files there are few manual steps to keep it in sync with upstream istio.

I will add Gateway's resources to our APIs as we are starting to use it internally in few internal projects.
